language: go

go:
  - 1.15.6

services:
  - docker

install: skip

jobs:
  include:
  - os: linux
    env: TEST_INSTANCE=test-alpine-go
  - os: linux
    env: TEST_INSTANCE=test-alpine-go
  - os: linux
    env: TEST_INSTANCE=test-alpine-nolfs-go
  - os: linux
    env: TEST_INSTANCE=test-corehookspath-go
  - os: linux
    env: TEST_INSTANCE=test-whitespace-go
  - os: linux
    env: TEST_INSTANCE=test-rules
  - os: windows
    env: TEST_INSTANCE=test-windows

script:
  - sh "tests/${TEST_INSTANCE}.sh"